# add stages here
stages:
  load_data:
    cmd: python src/stage_01_load_save.py
    deps:
    - src/stage_01_load_save.py
    - src/utils/common.py
    outs:
    - data

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/common.py
      - src/utils/models.py
      - data
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/base_model/inceptionv3_base_model.h5
      - artifacts/base_model/updated_inceptionv3_base_model.h5

  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py
    deps:
      - src/stage_03_prepare_callbacks.py
      - src/utils/common.py
      - src/utils/callbacks.py
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
      - artifacts/callbacks/earlystop_cb.cb
      - artifacts/callbacks/csvlogger_cb.cb

  train:
    cmd: python src/stage_04_train.py
    deps:
      - src/stage_04_train.py
      - src/utils/common.py
      - src/utils/models.py
      - src/utils/callbacks.py
      - src/utils/data_management.py
      - data
      - artifacts/base_model/updated_inceptionv3_base_model.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
      - artifacts/callbacks/earlystop_cb.cb
      - artifacts/callbacks/csvlogger_cb.cb
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/model