# add stages here
stages:
  load_data:
    cmd: python src/stage_01_load_save.py
    deps:
    - src/stage_01_load_save.py
    - src/utils/
    outs:
    - data

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/
      - data
    outs:
      - artifacts/base_model/inceptionv3_base_model.h5
      - artifacts/base_model/updated_inceptionv3_base_model.h5