# This contains params to be used by the stages to train or predict
preprocess:
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2   
  validation_split: 0.2 
  img_width: 224
  img_height: 224
  color_mode: 'rgb'
  class_mode: 'categorical' 
  shuffle: True 
  seed: 1337
  do_data_augmentation: True

model:
  BASE_MODEL: "InceptionV3"
  EPOCHS: 30
  CLASSES: 120
  LEARNING_RATE: 0.001
  BATCH_SIZE: 64
