# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: inceptionv3_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_inceptionv3_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: dataset

  local_data_dirs:
    TRAIN_DATA_DIR:  \dataset\archive\images\Images
