name: stanford-dogs-dataset-classification

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: cml-run
        env:
          repo_token: ${{ secrets._GITHUB_TOKEN }}
        run: |
          # Your ML wokflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro -v
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          echo "### Validation Accuracy" >> report.md
          cml artifacts\model_eval_metrics_dir\baseline_acc_epoch.png --md >> report.md
          echo "### Validation Loss" >> report.md
          cml artifacts\model_eval_metrics_dir\baseline_loss_epoch.png --md >> report.md
          cml-send-comment report.md